spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 685702242020-va2nea7li49u9kmtssesopgqes6ii921.apps.googleusercontent.com
            client-secret: 7HWhsuGt8UE0iaJ-AyxD8zCG
  datasource:
    url: jdbc:postgresql://db:5432/demo
    username: postgres
    password: kI_f315KueN
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://db:5432/demo
    username: postgres
    password: kI_f315KueN
logging:
  level:
    org.springframework.security: debug
