spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: stub-id
            client-secret: stub-secret
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
logging:
  level:
    org.springframework.security: debug
